### ISSUE TITLE
depreacated by microscope right

### ISSUE THREAD

**Issue by carandraug** [MicronOxford/cockpit-lasers#2]
I'm looking at this and I think this is all done by microscope now correct? If so, I will remove this repository.

**Comment by iandobbie** [comment]
Please don’t remove it now. Although this should all be done by microscope I’m not sure if we are currently using this code on CryoSIM. I’ll check it out and get back to you.

Ian

Sent from my iPhone

On 19 Jun 2018, at 12:30, Carnë Draug <notifications@github.com<mailto:notifications@github.com>> wrote:


I'm looking at this and I think this is all done by microscope now correct? If so, I will remove this repository.

**Comment by mickp** [comment]
I've marked the project as deprecated in the readme, with directions to MicronOxford/microscope, and will archive it - it'll still be available, but will be read only.
